spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:dbtest
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      pool-name: POOL_H2
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 120000
      max-lifetime: 28800000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update